# Copyright (c) 2024-2025 Brian Lin
# SPDX-License-Identifier: Apache-2.0

idog_gazebo:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000

    # FL Controllers ---------------------------------------
    FL_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_hip_joint #LF_HAA

    FL_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_thigh_joint #LF_HFE

    FL_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: FL_calf_joint #LF_KFE

    # FR Controllers ---------------------------------------
    FR_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_hip_joint #RF_HAA

    FR_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_thigh_joint #RF_HFE

    FR_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: FR_calf_joint #RF_KFE

    # RL Controllers ---------------------------------------
    RL_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: RL_hip_joint #LH_HAA

    RL_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: RL_thigh_joint #LH_HFE

    RL_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: RL_calf_joint #LH_KFE

    # RR Controllers ---------------------------------------
    RR_hip_controller:
        type: robot_joint_controller/RobotJointController
        joint: RR_hip_joint #RH_HAA

    RR_thigh_controller:
        type: robot_joint_controller/RobotJointController
        joint: RR_thigh_joint #RH_HFE

    RR_calf_controller:
        type: robot_joint_controller/RobotJointController
        joint: RR_calf_joint #RH_KFE

